version: '3.8'
services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: new-vet-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - vet-app-network

  spring-app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/new-vet-app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - vet-app-network

networks:
  vet-app-network:
